//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatePersonale
    {
        public int StudentId { get; set; }
        public Nullable<int> id { get; set; }
        public string Oras { get; set; }
        public string Liceu { get; set; }
    
        public virtual test test { get; set; }
    }
}
